name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Test on different platforms
  platform-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install cmake-js and dependencies
      run: |
        npm install -g cmake-js
        if [ "${{ runner.os }}" = "Windows" ]; then
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        elif [ "${{ runner.os }}" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libxtst-dev libpng++-dev
        elif [ "${{ runner.os }}" = "macOS" ]; then
          brew install cmake
        fi

    - name: Build and test
      run: |
        node scripts/build-all.js
        npm test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-node-${{ matrix.node-version }}
        path: |
          build/
          nut-core/build/
